# Generated by Django 5.0 on 2024-01-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
