# Generated by Django 5.0 on 2024-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='score',
        ),
        migrations.AddField(
            model_name='user',
            name='score_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
