# Generated by Django 5.0 on 2024-02-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_rank_user_score_user_score_time_user_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
