# Generated by Django 5.0 on 2024-02-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_name_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
