# Generated by Django 5.0 on 2024-02-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.CharField(blank=True, null=True),
        ),
    ]
