# Generated by Django 5.0 on 2024-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_room_room_roomnum_room_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
