# Generated by Django 5.0 on 2024-02-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
